## Import dataset

In [2]:
import pandas as pd

In [3]:
df_con = pd.read_csv('All - Itemized Contributions Received Of Over $200 - Campaign Finance.csv')

In [4]:
df_gen = pd.read_csv('All - Itemized General Expenditures and Contributions Made Of Over $200 - Campaign Finance.csv')

/var/folders/bz/72zd2hjs5t5drbxxvfh0xhph0000gn/T/ipykernel_97285/1432785334.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df_gen = pd.read_csv('All - Itemized General Expenditures and Contributions Made Of Over $200 - Campaign Finance.csv')


In [5]:
df_ind = pd.read_csv('All - Itemized Independent Expenditures Of Over $200 - Campaign Finance.csv')

/var/folders/bz/72zd2hjs5t5drbxxvfh0xhph0000gn/T/ipykernel_97285/1647704916.py:1: DtypeWarning: Columns (13,17) have mixed types. Specify dtype option on import or set low_memory=False.
  df_ind = pd.read_csv('All - Itemized Independent Expenditures Of Over $200 - Campaign Finance.csv')


In [19]:
df_con.head

<bound method NDFrame.head of         Recipient reg num                                 Recipient  \
0                   17319          Hoffman, John A Senate Committee   
1                   18690            Jensen, Scott Dr Gov Committee   
2                   18690            Jensen, Scott Dr Gov Committee   
3                   20013                 Senate Victory Fund (SVF)   
4                   41297  Progressive Turnout Project Victory Fund   
...                   ...                                       ...   
134692              18135                   Walz, Tim Gov Committee   
134693              18690            Jensen, Scott Dr Gov Committee   
134694              18742             Qualls, Kendall Gov Committee   
134695              18709           Helseth, Marla Senate Committee   
134696              40019                          Food PAC of Minn   

       Recipient type Recipient subtype  Amount Receipt date  Year  \
0                 PCC               NaN   300.0

## Check for unique contribution types, recipient types, and recipients, 

In [20]:
df_con['Contrib type'].unique()

array(['Individual', 'Political Committee/Fund', 'Other', 'Party Unit',
       'Lobbyist', 'Candidate Committee', 'Self', 'Unknown/Null',
       'Registered with Hennepin County', nan], dtype=object)

In [6]:
df_con['Recipient type'].unique()

array(['PCC', 'PTU', 'PCF'], dtype=object)

In [7]:
df_con['Recipient'].unique()

array(['Hoffman, John A Senate Committee',
       'Jensen, Scott Dr Gov Committee', 'Senate Victory Fund (SVF)', ...,
       'Neighbors for Anoka County', '38th Senate District DFL (Old)',
       '66A House District RPM'], dtype=object)

In [8]:
import sys
import numpy
numpy.set_printoptions(threshold=sys.maxsize)

In [9]:
df_con['Recipient'].unique()

array(['Hoffman, John A Senate Committee',
       'Jensen, Scott Dr Gov Committee', 'Senate Victory Fund (SVF)',
       'Progressive Turnout Project Victory Fund',
       'Otto, Rebecca Gov Committee', 'Seeberger, Judy Senate Committee',
       'Hauschild, Grant Senate Committee', 'Walz, Tim Gov Committee',
       'Faegre Drinker State Political Fund',
       'MEDPAC Minn Medical Political Action Comm', 'DGA Victory Fund',
       'Thissen, Paul C House Committee',
       'Simon, Steve Sec of State Committee',
       'Wilson, Ryan State Aud Committee',
       'Preese, Erin B House Committee',
       'Winkler, Ryan Atty Gen Committee',
       'Robbins, Kristin House Committee',
       'Schultz, James Atty Gen Committee', 'DLCC for Minnesota',
       'Johnson, Jeff R Gov Committee', 'Wilde, Amy Senate Committee',
       'Benson, Michelle R Senate Committee',
       'Clardy, Mary Frances House Committee',
       'Hansen, Richard (Rick) J House Committee',
       'Fenton, Kelly House Commit

In [12]:
# Check if indeed all 3 csv files cover all years from 2015 to present

print(df_con['Year'].unique())
print(df_gen['Year'].unique())
print(df_ind['Year'].unique())

[2022 2017 2016 2018 2020 2015 2019 2023 2021]
[2015 2016 2017 2018 2019 2020 2021 2022 2023]
[2022 2018 2020 2019 2016 2017 2015 2023 2021]


## Check itemized file for subtype details

In [13]:
df_com_fun = pd.read_csv('Itemized contributions seperate/Committees and Funds - Itemized Contributions Received Of Over $200 - Campaign Finance.csv')

In [14]:
df_com_fun['Recipient subtype'].unique()

array(['PF', 'PC', 'PCN', 'PFN', 'IEF', 'IEC', 'BC'], dtype=object)

In [15]:
df_ind_com_fun = pd.read_csv('Itemized contributions seperate/Independent Expenditure Committees and Funds - Itemized Contributions Received Of Over $200 - Campaign Finance.csv')

In [16]:
df_ind_com_fun['Recipient subtype'].unique()

array(['IEF', 'IEC'], dtype=object)

## All registered candidate committees

In [17]:
df_reg_cand = pd.read_csv('All registered candidate committees.csv')

In [18]:
df_reg_cand['Office sought'].unique()

array(['House', 'Senate', 'Governor', 'Secretary of State',
       'Attorney General', 'State Auditor', 'District Court'],
      dtype=object)